### ISSUE TITLE
Interface operation and admin status are wrong

### ISSUE THREAD

**Issue by netcoms** [solarwinds/orionsdk-python#16]
When using DiscoverInterfacesOnNode verb i'm getting all interfaces with ifOperStatus = 4 and ifAdminStatus = 0 regardless if the interface is up or not. Can you please correct that

**Comment by tdanner** [comment]
This (embarrassing) issue is tracked internally as NPM-6293.

**Comment by multipl3x** [comment]
Guys, I know this is an old bug, but we are still having this problem in a recent version of NPM (12.2) and this really hinders the usability of the SDK in that we can't pull in the interfaces that most people need, which are going to be primarily UP interfaces. Would you guys consider taking a second look at this?   
    
I am willing to contribute whatever time or resources I can in order to move this forward. 

Thanks!

**Comment by tdanner** [comment]
This has been fixed in NPM 12.4. ifAdminStatus and ifOperStatus are now reported correctly for DiscoverInterfacesOnNode.
