### ISSUE TITLE
SwisClient "SELECT *" Issue

### ISSUE THREAD

**Issue by SMaiorino** [solarwinds/orionsdk-python#47]
Previously, the SwisClient supported invoking SELECT statements using the '*' wildcard to query all results from a specific table.

Ex.

sw = SwisClient('server', 'user', 'pword')
q = sw.query('SELECT * FROM Orion.Nodes')

This above code returns an error (see attached) that basically says the '*' character cannot be used as input. Has support for this wild card been taken away? I've tried this using python 3.7 and python 2.7.17 and received the same error.
![sw_error](https://user-images.githubusercontent.com/28761056/71626798-06bbb680-2bbd-11ea-8d0e-cbd9e49734be.PNG)

**Comment by superadm1n** [comment]
Im not sure if SWQL ever supported a wildcard, per the article at https://support.solarwinds.com/SuccessCenter/s/article/Use-SolarWinds-Query-Language-SWQL it states the following.

![swql](https://user-images.githubusercontent.com/32282453/71631883-f01f5a80-2bd0-11ea-8800-f15e25d34a49.PNG)

Based on this information you will need to specify the columns you want to pull explicitly, see the example below.

`SELECT NodeID, IPAddress, Caption
FROM Orion.Nodes`

I have tested both in SWQL studio and in Python3 and that is the case in each instance. I believe (might be incorrect) this is because how the SWQL language was designed and implemented and is expected behavior.

**Comment by SMaiorino** [comment]
This is very helpful...thank you. I can now at least look at this documentation to see the available properties for the SWQL. I honestly didn't even know it was called "SWQL" and thought the querying through python was an identical wrapper for regular SQL...maybe I'm remembering wrong and the wildcard '*' didn't used to work in the past. 

Anyways, thanks for sharing that link to the SWQL documentation, I never knew it existed.

**Comment by superadm1n** [comment]
Your welcome, another useful tool that I use all the time to help construct different queries and exploring the data and operations available via SWQL is SWQL Studio, you can download it here.

https://support.solarwinds.com/SuccessCenter/s/article/Download-the-SolarWinds-Orion-SDK 

I highly recommend it as I have found it speeds up the process of developing the correct query your looking for.

**Comment by SMaiorino** [comment]
I will try it out, thanks.

**Comment by danjagnow** [comment]
It looks like this question has been addressed, so I'm going to close out the issue.
