### ISSUE TITLE
snmp-testing

### ISSUE THREAD

**Issue by edurguti** [solarwinds/orionsdk-python#53]
Hi,  this is not an issue, just a question that I can't seem to find it anywhere. Is there a way to test the assigned snmp-credentials to a node are correct? Just like the 'test' button on the "Edit Node" section.
Thank you.

**Comment by mrxinu** [comment]
Hey @edurguti, I've never come across anything like that. I would take the community string and try to do a quick GET to pull the sysoid from the device. If it fails, the credential doesn't work. That's essentially what that test button is doing.

**Comment by edurguti** [comment]
Hi, thanks for your reply, I am thinking the same but it would just mean that the device is responding to my query but not it solarwinds can actually poll it or if it has the correct snmp credentials. I’ll probably end up doing that if there’s no other way.

**Comment by nothrow** [comment]
The "test credentials" button actually does GET on `sysObjectId` OID (so if device does not respond to it, it can't be polled by Orion).

There is one solution that does not involve hacking internals - you can execute verb `Orion.NPM.Interfaces.DiscoverInterfacesOnNode` with given NodeID, and if it returns something meaningful, credentials are correct. It has few cons, biggest one is that it is not very effective, since it requires extended communication with the device, and when device has thousand of interfaces, it can take quite a while.

**Comment by edurguti** [comment]
Thanks for your reply, yeah that will take a long time, I ended up using easysnmp to verify if the device responds.

```
from easysnmp import snmp_get

def is_snmp_ok(ip_address):
    try:
        #try to get device hostname
        snmp_get('sysName.0',hostname=f'{ip_address}', version=3,
        security_level="auth_with_privacy", security_username="myUser",
        auth_protocol="SHA", auth_password="MyAuth",
        privacy_protocol="AES", privacy_password="myPrivPass")
        return True
        #there is a bug in easysnmp that throws an invalid exception if the device doesn't exist.
    except Exception as _:
        return False
        
print(is_snmp_ok('10.82.0.59'))
```
```
time python test_snmp.py
True
python test_snmp.py  0.10s user 0.02s system 20% cpu 0.550 total
```
It's quite fast.

**Comment by mrxinu** [comment]
@edurguti Very nice! Saving that for later myself. If this is all good, can you go ahead and close it? :)
